name: New site support request
description: Request support for a site that is not currently supported by the script
title: '[New Site]'
labels: new site
body:
  - type: dropdown
    attributes:
      label: Site based on
      options:
        - NexusPHP
        - UNIT3D
        - Gazelle
        - Other
    validations:
      required: true
  - type: textarea
    id: upload-page-config
    attributes:
      label: Site Configuration
      description: A green "[EASY-UPLOAD] Retrieve Site Config" button will appear in the lower right corner of the site upload page. Click it and paste it here
      placeholder: |
        ```yaml
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
    validations:
      required: false
