name: New site support request(站点支持请求)
description: 发布一个脚本目前还没进行支持的站点
title: "[新站点]"
labels: ["new site"]
body:
  - type: textarea
    id: url
    attributes:
      label: 站点地址
    validations:
      required: true
  - type: dropdown
    id: based
    attributes:
      label: 站点架构
      options:
        - NexusPHP
        - UNIT3D
        - Gazelle
        - Other
    validations:
      required: true
  - type: textarea
    id: upload-page-config
    attributes:
      label: 站点配置
      description: 在站点上传页面右下角会出现一个绿色的"[EASY-UPLOAD]获取页面配置"按钮，点击后黏贴到这里
      placeholder: |
        ```yaml
        ```
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 其他
    validations:
      required: false
