url: https://hawke.uno
host: hawke.uno
siteType: UNIT3D
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAADOklEQVR4nL1U32/TVhT+kpUXeIAW/gd4Ytr+gT1XCBC/JJAm8RYJTaNqrmP73sRxC+w/mJCmTUKa4AUhBLET0rERDbQ9dR1FRRRBW8UJELa2lC52nNj1QddpsoYB2st2pE86Oj76fI6+7x7gf4gEiLp4TxBRQiLufW/IhkplCNhKJGsU1whIVExzaCtJr0b0NrFJyf5EREkU1vfgOu2O6z3izR+Zppms6/ruZ+n0HjLNZH/izbxLJsNeG4bdzMNy52B7q7C8FVjebNJqckzRDmKf71higteZmK0pYqXGxKrD+JzDeL6q68MxcZ+0sL4PRf8J7hLh9sYGii2K8UMYJX4lwrXl2XtfarOReYFe6vmormSprgj6U89vuMYFmT9ZSvN9XbIr1WFMBY9QIULB9VH0QvxEFMP2gmSp1QH7nvafVOkpE53nighW+AStigmqKSJ0GPdfZyepoRmPHpw5Mwzcak/EkxWabdzqEMptH5Zr4cZ6CRXq4Otp+mj0ixCH1TCfEuRzo7OQ1ktVxq2GlvNfqDmqMt6Wk77IGBNAuTOPckCw3Qh2K0DBH+2L9TMdw9lvKXlwLMIRLfrklE6vFHGs97nGxGhdEYGjiKihGtRQs/OA7UWw3BB3iGB5dtz5zfQ2mNJCAI5kKjiRJZwQlJC51PEzc2g6ldomc0fh9pqYJIfxsKaIaJCw4BZjEum9HuHRdxNS15NwGC++GiDsrWy5EYqtEHbzQH/lu3QcY9/1V/5Urqzmjv+9snagLoWRK2tyZWMeKHpGLIolRWkTyp02brol3PyrjDsU4OJvXVEOqeFkilNLzwULjJerab3UUHPtWJS03naN8/RczRnApaVdmAoe9m0jhZGW+XGLbZTL9PFJlRaZ6DzbYptYEMb99ew5eqkZD38/PbarO/uN13theY8Hje13jf1LbOyZe2f1mcj8iv7QzaieyZLE8qaxa4p4vDiW2Tv49G6v7oTdzMH27sP2lmNY3kzSbmoo0HZKpbYvMqHVGJ9xmFiOofD7TiabW9C0nb13/q7jkECZRnB1bWSgtpnLCzM3Pj7ijI+PyBz/OA4fOl9xbfB89Ug+fL7ejn9/YP/7eAMLS3CiKim0CAAAAABJRU5ErkJggg==
asSource: true
asTarget: true
uploadPath: /torrents/create?category_id=1
torrentDownloadLinkSelector: a[href*="/torrents/download/"]
needDoubanInfo: true
seedDomSelector: .torrent__buttons+.panelV2
search:
  path: /torrents
  replaceKey:
    - tt
    - ""
  params:
    name: "{name}"
    imdbId: "{imdb}"
    sortField: size
name:
  selector: input[name="name"][class="form__text"]
description:
  selector: "#bbcode-description"
imdb:
  selector: "#autoimdb"
tmdb:
  selector: "#autotmdb"
mediaInfo:
  selector: textarea[name="mediainfo"]
anonymous:
  selector: .form__group input[type="checkbox"][name="anon"]
torrent:
  selector: input[type="file"][accept=".torrent"]
category:
  selector: "#browsecat"
  map:
    movie: "1"
    tv: "2"
    tvPack: "2"
videoType:
  selector: "#autotype"
  map:
    uhdbluray: "1"
    bluray: "1"
    remux: "3"
    encode: "12"
    web: "4"
    hdtv: "6"
    dvd: "1"
    dvdrip: "12"
    other: ""
resolution:
  selector: "#autores"
  map:
    4320p: "11"
    2160p: "1"
    1080p: "2"
    1080i: "3"
    720p: "5"
    576p: "6"
    480p: "8"
