url: https://lemonhd.club
host: lemonhd.club
siteType: NexusPHP
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAPoAAAD6AG1e1JrAAADkUlEQVR4nI2Uf0zUdRjHnzt+CExYwQwbDLChy3TLcrVJqMtNaNRaWWBzZbMhPyLQNoKMk6PmbGVYzIYYakq1OcosS+qPmq11gKKAguF5Id1xAgGCVhr6/X4/r3Z3IMc8imf77vnj+Xxfn/fzfd7PV+R/gvrMIMAUsIanJgFr08K8WcRM16MpnFuayZnkZ3E8ns4vMZE+qNU8I6jnoDefT8+i9/UO+jYprlfD2EHFYBG4S/uUY00ZVgn2dPCf0Fuw7vVvcX0nuLIULYkGjnwN13aN5rsNHGkG/5SDs/AYlRLuey8AdKJNZU/dyNguGP1Goz1Vwxav+K0EXDugeQE0JRn0770BDdCd9rG/ED9lvhv4XqIZtPTiWA2tqQajP8PpZWDPA+e70BgPg4fBWanU6WSd0QqwL1weoNXxITjTsxgpRZ1M1GlKhrMZMPAZ9FRAz5vQ+z5ctEDTPajGOJ2hbHC/tCfQtwv2ZK0np4qrZdC+QqNjDbStAns+/P0rXLvgU9m2EjqeRrWv0hnIhksFP94GrGp4bJYX7MrfCT/B0Fcaw8dg6GsY+hL0v0AZcPk7X8vDDajBIzqGDVxFU4GZmeJtV0TCWhozDjG8CaN5ns7JxXDiPujbD/0HYPALH+zUQ3BiIao5Wcf1JDg3+gGt4p1OyFrJkXVyednWCOivUMap+dDyIAwfha4NcD4beqzQuRaGv4XW5dAUq3G1FNxZFh9rHJZUFmFZuXsOD1fGGHOLzZxtfQ7chejuKnAUg20udL8GrkqwxcKFQuj/xMDxFAxs/pPGqORJhRtkffirQSx9504ta3+8nvJBLI98ZGJ0YAf0vc1NWyR6Y6LCXqT4fbuiaZ6BLUqjd6vBjUPQlpAz6eEX5Q7JFWdMcSiLtkVpK96bo4JKBKkR0urDudaTDQNWxbkUhXsL/LELupYoRgqhN8/gzP0FU02dK0mmXLliKhASyiNUdEmoHlcTrtKPxvJAfQwL6kJU+Q+LDLt9nYb7jREuWa4o18suLj6/j875S/y3azJyJEHy5JmgFyRDtogldJ+ZuIPhavWRu7RZtWZNDgiRNbIZq5g7ayWa4xLmt13m2/w3PmmvqaVW8kM/NRNXF3bz3sORzK4LxlQt2wJt1fQwxCSF4jW17JZXgj83EVJrGpNqOS57JHXCDZ5dn3gCg6aG79CHMluq5YmQall8q1LvNf3M/8zThkeJDzbj+Bc9TIk5RyzZEgAAAABJRU5ErkJggg==
asSource: true
asTarget: true
uploadPath: /upload.php
seedDomSelector: "#top~table:first>tbody>tr:nth-child(5)"
torrentDownloadLinkSelector: a[href*="download.php?id="]
search:
  path: /torrents.php
  imdbOptionKey: "4"
  nameOptionKey: "0"
  params:
    incldead: "0"
    search_area: "{optionKey}"
    search: "{imdb}"
    sort: "5"
    type: desc
  result:
    list: "#torrenttable>tbody>tr"
    url: '.torrentname td a[href*="details.php?id="]'
    name: '.torrentname td a[href*="details.php?id="]'
    size: "td:nth-child(5)"
name:
  selector: input[name="name"]
subtitle:
  selector: input[name="small_descr"]
description:
  selector: textarea[name="descr"]
imdb:
  selector: input[name="imdb"]
douban:
  selector: input[name="douban"]
anonymous:
  selector: 'input[name="uplver"]'
torrent:
  selector: 'input[name="file"]'
mediainfo:
  selector: textarea[name="mediainfo"]
category:
  selector: select[name="type"]
  map:
    movie: "401"
    tv: "402"
    tvPack: "402"
    documentary: "404"
    concert: "406"
    sport: "407"
    cartoon: "405"
    variety: "403"
    music: "411"
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: "1"
    x264: "1"
    hevc: "3"
    x265: "3"
    h265: "3"
    mpeg2: "4"
    mpeg4: "1"
    vc1: "2"
    xvid: "100"
    dvd: "4"
audioCodec:
  selector: 'select[name="audiocodec_sel"]'
  map:
    aac: "8"
    ac3: "6"
    dd: "6"
    dd+: "7"
    flac: "10"
    dts: "5"
    truehd: "2"
    lpcm: "9"
    dtshdma: "3"
    atmos: "1"
    dtsx: "4"
    ape: "12"
    wav: "11"
    mp3: "100"
    m4a: "100"
    other: "100"
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray: "3"
    bluray: "1"
    remux: "12"
    encode: "13"
    web: "10"
    hdtv: "11"
    dvd: "2"
    dvdrip: "13"
    other: 5"
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    4320p: "6"
    2160p: "5"
    1080p: "1"
    1080i: "2"
    720p: "3"
    576p: "100"
    480p: "4"
area:
  selector: select[name="team_sel"]
  map:
    CN: "3"
    US: "1"
    EU: "1"
    HK: "2"
    TW: "2"
    JP: "4"
    KR: "4"
    IN: "5"
    OT: "10"
tags:
  chinese_audio: input[name="tag_gy"]
  diy: input[name="tag_diy"]
  cantonese_audio: input[name="tag_yy"]
  chinese_subtitle: input[name="tag_zz"]
  hdr: input[name="tag_hdr"]
  dolby_vision: input[name="tag_dv"]
