url: https://bilibili.download
host: bilibili.download
siteType: NexusPHP
asSource: false
asTarget: true
uploadPath: /upload.php
search:
  path: /torrents.php
  imdbOptionKey: "4"
  nameOptionKey: "0"
  params:
    incldead: 1
    search_area: "{optionKey}"
    search: "{keyword}"
name:
  selector: input[name="name"]
subtitle:
  selector: input[name="small_descr"]
imdb:
  selector: input[name="url"][type="text"]
description:
  selector: textarea[name="descr"]
douban:
  selector: input[name="pt_gen"]
torrent:
  selector: "#torrent"
anonymous:
  selector: input[name="uplver"]
category:
  selector: select[name="type"]
  map:
    movie: "401"
    tv: "402"
    variety: "403"
    documentary: "404"
    cartoon: "405"
    sport: "407"
    music: "408"
    software: "410"
    learning: "411"
    game: "412"
    comic: "419"
videoType:
  selector: select[name="medium_sel[4]"]
  map:
    uhdbluray: "2"
    bluray: "1"
    remux: "3"
    web: "4"
    hdtv: "5"
    dvd: "6"
    encode: "7"
    cd: "8"
videoCodec:
  selector: select[name="codec_sel[4]"]
  map:
    h264: "1"
    h265: "2"
    hevc: "2"
    vc1: "3"
    mpeg2: "4"
    xvid: "5"
    other: "6"
resolution:
  selector: select[name="standard_sel[4]"]
  map:
    4k: "1"
    2k: "6"
    2160p: "1"
    1080p: "2"
    1080i: "2"
    720p: "3"
    sd: "4"
    other: "5"
audioCodec:
  selector: select[name="audiocodec_sel[4]"]
  map:
    truehd: "1"
    atmos: "1"
    dtshdma: "2"
    dts-hd: "2"
    dts: "2"
    ac3: "3"
    lpcm: "4"
    flac: "5"
    mp3: "6"
    aac: "7"
    ape: "8"
    wav: "10"
    other: "9"
tags:
  hdr10: input[name="tags[4][]"][value="7"]
  diy: input[name="tags[4][]"][value="4"]
  cantonese_audio: input[name="tags[4][]"][value="5"]
  chinese_subtitle: input[name="tags[4][]"][value="6"]
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAPoAAAD6AG1e1JrAAACtElEQVR4nLWVa08TQRSGK0T8Ocav8h80JPLFSyjtdrcUNKJVkdsGvIB0W7otQhsbQARDalAwKCai4gUJSjCimPDFP8J2HjMzBaS0xsTY5GTOnPOed892zrzr85X8sO0q6uur/8psu6q0fo/Ix6E/AirV2XaVrK2UrCHgHCOYqCXkHCc4UKtM+jv7XT9Rq7C2XVPSmU+xi/PuEYKxOaw0mK7AdCHkSh/MFFgp9sdcobABZxY7X7PLRX2+Wm2sZB3NGUQw7tHoFAinCrSNFpQvLVBcZSzsKl9hIxkwknWKQ3LtEAojHsIakk/cxoiDkYCu+9A+Cuagtuuj0DWucxLT6GwTHkIYg6EDhAQThnwF0ZL26J7QZPaENunLWO+kXjvH1aqwhgtBxyhD6GjCm1Me0awEyW7hcgaaVJHuSlo4CVfvIXoeeERzCKtch6d6DfryiOUNj5kliLjQOgyP38LFYQjGIZQAfwxy87C4hlj57rG4jogUCfOlhLemEZs/PXLP4OkyPF+B+WWYfQcLK/DwJSytw4ev8GIVsbDqqSZOdB/sUAa5O49Y3/J49AY+/9CFr9fg4wZ82YJPm/pBK9/gShbx5L2HPYmov1Hmlc/0GbSNI+7kPZw89ExA64heX62BPQ7RDFxI6//VHET0T3u0jCAaBsoQmgmDUArROeapsTh9G871Q2MMmpJwtk/v/QPab04jOsY8dZCBeKjyKUezHr1T0DGmTc7etZyeR2ky1j4GPZMaa6WRI1d+sMMy6WwTSaFIJYE84UsZaM1oX8ZkTmIkNpyuMNiWe1JdPaN49cxkgUC8QEOsgP83kzGZ27l6zaVXrygOmNnDBJwZJQJWSmAmwXK1KISL4qAEoigSZkqofTA2t08c9imPJLXiR7GK8uUvSlU5qyRfezL2HwR2F/APn4BfcLtDzdF35wEAAAAASUVORK5CYII=
